-- CreateTable
CREATE TABLE "ROLE" (
    "RoleID" SERIAL NOT NULL,
    "RoleName" TEXT NOT NULL,

    CONSTRAINT "ROLE_pkey" PRIMARY KEY ("RoleID")
);

-- CreateTable
CREATE TABLE "USERS" (
    "UserID" SERIAL NOT NULL,
    "Username" TEXT NOT NULL,
    "RoleID" INTEGER NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("UserID")
);

-- CreateTable
CREATE TABLE "PERMISSION" (
    "PermissionID" SERIAL NOT NULL,
    "PermissionName" TEXT NOT NULL,

    CONSTRAINT "PERMISSION_pkey" PRIMARY KEY ("PermissionID")
);

-- CreateTable
CREATE TABLE "USER_PERMISSION" (
    "UserID" INTEGER NOT NULL,
    "PermissionID" INTEGER NOT NULL,

    CONSTRAINT "USER_PERMISSION_pkey" PRIMARY KEY ("UserID","PermissionID")
);

-- CreateTable
CREATE TABLE "ITEM" (
    "SKU" TEXT NOT NULL,
    "ItemName" TEXT NOT NULL,

    CONSTRAINT "ITEM_pkey" PRIMARY KEY ("SKU")
);

-- CreateTable
CREATE TABLE "WAREHOUSE" (
    "WarehouseID" TEXT NOT NULL,
    "WarehouseName" TEXT NOT NULL,

    CONSTRAINT "WAREHOUSE_pkey" PRIMARY KEY ("WarehouseID")
);

-- CreateTable
CREATE TABLE "INVENTORY" (
    "SKU" TEXT NOT NULL,
    "WarehouseID" TEXT NOT NULL,
    "AvailableStock" INTEGER NOT NULL,

    CONSTRAINT "INVENTORY_pkey" PRIMARY KEY ("SKU","WarehouseID")
);

-- CreateTable
CREATE TABLE "RESTOCKING_REQUEST" (
    "RequestID" TEXT NOT NULL,
    "SKU" TEXT NOT NULL,
    "WarehouseID" TEXT NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "Priority" TEXT NOT NULL,
    "Justification" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    "RequestedBy" INTEGER NOT NULL,
    "DecidedBy" INTEGER,
    "CreatedAt" TIMESTAMP(3) NOT NULL,
    "DecisionAt" TIMESTAMP(3),
    "RejectionReason" TEXT,
    "CorrectionNote" TEXT,

    CONSTRAINT "RESTOCKING_REQUEST_pkey" PRIMARY KEY ("RequestID")
);

-- CreateTable
CREATE TABLE "ALLOCATION" (
    "AllocationID" TEXT NOT NULL,
    "RequestID" TEXT NOT NULL,
    "SKU" TEXT NOT NULL,
    "QuantityAllocated" INTEGER NOT NULL,
    "Status" TEXT NOT NULL,
    "Timestamp" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ALLOCATION_pkey" PRIMARY KEY ("AllocationID")
);

-- CreateTable
CREATE TABLE "AUDIT_TRAIL" (
    "AuditID" TEXT NOT NULL,
    "RequestID" TEXT NOT NULL,
    "Action" TEXT NOT NULL,
    "PreviousStatus" TEXT,
    "NewStatus" TEXT,
    "PerformedBy" INTEGER NOT NULL,
    "Timestamp" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AUDIT_TRAIL_pkey" PRIMARY KEY ("AuditID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_Username_key" ON "USERS"("Username");

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_RoleID_fkey" FOREIGN KEY ("RoleID") REFERENCES "ROLE"("RoleID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_PERMISSION" ADD CONSTRAINT "USER_PERMISSION_UserID_fkey" FOREIGN KEY ("UserID") REFERENCES "USERS"("UserID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_PERMISSION" ADD CONSTRAINT "USER_PERMISSION_PermissionID_fkey" FOREIGN KEY ("PermissionID") REFERENCES "PERMISSION"("PermissionID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY" ADD CONSTRAINT "INVENTORY_SKU_fkey" FOREIGN KEY ("SKU") REFERENCES "ITEM"("SKU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY" ADD CONSTRAINT "INVENTORY_WarehouseID_fkey" FOREIGN KEY ("WarehouseID") REFERENCES "WAREHOUSE"("WarehouseID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESTOCKING_REQUEST" ADD CONSTRAINT "RESTOCKING_REQUEST_RequestedBy_fkey" FOREIGN KEY ("RequestedBy") REFERENCES "USERS"("UserID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESTOCKING_REQUEST" ADD CONSTRAINT "RESTOCKING_REQUEST_DecidedBy_fkey" FOREIGN KEY ("DecidedBy") REFERENCES "USERS"("UserID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESTOCKING_REQUEST" ADD CONSTRAINT "RESTOCKING_REQUEST_SKU_fkey" FOREIGN KEY ("SKU") REFERENCES "ITEM"("SKU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESTOCKING_REQUEST" ADD CONSTRAINT "RESTOCKING_REQUEST_WarehouseID_fkey" FOREIGN KEY ("WarehouseID") REFERENCES "WAREHOUSE"("WarehouseID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ALLOCATION" ADD CONSTRAINT "ALLOCATION_RequestID_fkey" FOREIGN KEY ("RequestID") REFERENCES "RESTOCKING_REQUEST"("RequestID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ALLOCATION" ADD CONSTRAINT "ALLOCATION_SKU_fkey" FOREIGN KEY ("SKU") REFERENCES "ITEM"("SKU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AUDIT_TRAIL" ADD CONSTRAINT "AUDIT_TRAIL_RequestID_fkey" FOREIGN KEY ("RequestID") REFERENCES "RESTOCKING_REQUEST"("RequestID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AUDIT_TRAIL" ADD CONSTRAINT "AUDIT_TRAIL_PerformedBy_fkey" FOREIGN KEY ("PerformedBy") REFERENCES "USERS"("UserID") ON DELETE RESTRICT ON UPDATE CASCADE;
